spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vector_db
    username: postgres
    password: admin
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      temperature: 0.3
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo
#      model: gpt-4-turbo
      embedding-base-url: https://api.openai.com
      embedding-api-key: ${OPENAI_API_KEY}
      embedding-model: text-embedding-ada-002

management:
  endpoints:
    web:
      exposure:
        include: "*"